In [38]:
import numpy as np
a =np.array([[3,2,-1],[2,-2,4],[-1,1/2,-1]])
print(a)

[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]


In [39]:
b = np.array([1,-2,0])
z = np.linalg.solve(a,b)
print(z)

[ 1. -2. -2.]


In [40]:
import numpy as np
from numpy.linalg import inv
a =np.array([[3,2,-1],[2,-2,4],[-1,1/2,-1]])
ainv = np.linalg.inv(a)
np.allclose(np.dot(a, ainv), np.eye(3))
b = np.array([[1],[-2],[0]])
print(a)
print(b)

[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]
[[ 1]
 [-2]
 [ 0]]


In [41]:
ainv = inv(np.matrix(a))
ainv

ans = np.dot(ainv,b)
print(ans)

[[ 1.]
 [-2.]
 [-2.]]
